RRD-ANTLR4: de.flashpixx.rrd_antlr4.engine.template.ITemplate Interface Reference
de.flashpixx.rrd_antlr4.engine.template.ITemplate Interface Reference
interface of a template
Public Member Functions
IGrammarComplexElement element (final IGrammarComplexElement p_grammar, final IGrammarComplexElement p_element)
is called if any grammar element is completed
IGrammarComplexElement grammar (final IGrammarComplexElement p_grammar)
is called on the grammar definition
String index ()
returns the index file
String name ()
returns the name of the template
void postprocess (final Path p_output) throws IOException, URISyntaxException
postprocessing (after AST visiting)
void preprocess (final Path p_output) throws IOException, URISyntaxException
preprocessing (before AST visiting)
Detailed Description
Definition at line 36 of file ITemplate.java.
Member Function Documentation
element()
IGrammarComplexElement de.flashpixx.rrd_antlr4.engine.template.ITemplate.element (final IGrammarComplexElement p_grammar, final IGrammarComplexElement p_element)
Parameters
p_grammar grammar
p_element element
Returns
grammar object reference
Implemented in de.flashpixx.rrd_antlr4.engine.template.CHTML, and de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.
Referenced by de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerRuleSpec(), and de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitParserRuleSpec().
grammar()
IGrammarComplexElement de.flashpixx.rrd_antlr4.engine.template.ITemplate.grammar (final IGrammarComplexElement p_grammar)
Parameters
p_grammar grammar
Returns
grammar object reference
Implemented in de.flashpixx.rrd_antlr4.engine.template.CHTML, and de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.
Referenced by de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitGrammarSpec().
index()
String de.flashpixx.rrd_antlr4.engine.template.ITemplate.index ()
Returns
index file name without path
Implemented in de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.
name()
String de.flashpixx.rrd_antlr4.engine.template.ITemplate.name ()
Returns
template name
Implemented in de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.
Referenced by de.flashpixx.rrd_antlr4.CCommon.outputdirectory().
postprocess()
void de.flashpixx.rrd_antlr4.engine.template.ITemplate.postprocess (final Path p_output) throws IOException, URISyntaxException
Parameters
p_output working directory
Exceptions
IOException on io errors
URISyntaxException on uri syntax
Implemented in de.flashpixx.rrd_antlr4.engine.template.CHTML, and de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.
preprocess()
void de.flashpixx.rrd_antlr4.engine.template.ITemplate.preprocess (final Path p_output) throws IOException, URISyntaxException
Parameters
p_output output directory
Exceptions
IOException on io errors
URISyntaxException on uri syntax
Implemented in de.flashpixx.rrd_antlr4.engine.template.CHTML, and de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.