RRD-ANTLR4: de.flashpixx.rrd_antlr4.TestCLanguageLabels Class Reference
de.flashpixx.rrd_antlr4.TestCLanguageLabels Class Reference
test all resource strings
Classes
class CJavaVistor
AST visitor class.
Public Member Functions
void testResourceString () throws IOException
test-case all resource strings
void testTranslation ()
check package translation configuration versus property items
Static Public Member Functions
static void main (final String[] p_args) throws IOException
main method
Static Package Functions
[static initializer]
Static Private Attributes
static final String CLASSSEPARATOR = "."
static final Map< String, URI > LANGUAGEPROPERY = new HashMap<>()
property filenames with language data
static final URI SEARCHPATH
search path
Additional Inherited Members
Protected Member Functions inherited from de.flashpixx.rrd_antlr4.IBaseTest
final void invoketest ()
invoke all test manually
Detailed Description
Definition at line 67 of file TestCLanguageLabels.java.
Member Function Documentation
[static initializer]()
de.flashpixx.rrd_antlr4.TestCLanguageLabels.[static initializer] () static package
main()
static void de.flashpixx.rrd_antlr4.TestCLanguageLabels.main (final String [] p_args) throws IOException static
Parameters
p_args arguments
Exceptions
IOException in file error
Definition at line 294 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.IBaseTest.invoketest().
testResourceString()
void de.flashpixx.rrd_antlr4.TestCLanguageLabels.testResourceString () throws IOException
Exceptions
IOException throws on io errors
Definition at line 174 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.labels(), de.flashpixx.rrd_antlr4.CCommon.PACKAGEROOT, and de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.visit().
testTranslation()
void de.flashpixx.rrd_antlr4.TestCLanguageLabels.testTranslation ()
Definition at line 130 of file TestCLanguageLabels.java.
References de.flashpixx.rrd_antlr4.CCommon.configuration().
Member Data Documentation
CLASSSEPARATOR
final String de.flashpixx.rrd_antlr4.TestCLanguageLabels.CLASSSEPARATOR = "." static private
Definition at line 69 of file TestCLanguageLabels.java.
LANGUAGEPROPERY
final Map<String, URI> de.flashpixx.rrd_antlr4.TestCLanguageLabels.LANGUAGEPROPERY = new HashMap<>() static private
Definition at line 77 of file TestCLanguageLabels.java.
SEARCHPATH
final URI de.flashpixx.rrd_antlr4.TestCLanguageLabels.SEARCHPATH static private
Definition at line 73 of file TestCLanguageLabels.java.