RRD-ANTLR4: de.flashpixx.rrd_antlr4.antlr.IGrammarSimpleElement< T > Interface Template Reference
de.flashpixx.rrd_antlr4.antlr.IGrammarSimpleElement< T > Interface Template Reference
a simple grammar element
Public Member Functions
< N > N get ()
return native value
boolean isValueAssignableTo (final Class<?>... p_class)
checkes assignable of the value
Public Member Functions inherited from de.flashpixx.rrd_antlr4.antlr.IGrammarElement
ECardinality cardinality ()
returns the cardinality
IGrammarElement cardinality (final ECardinality p_cardinality)
changes the cardinality
Detailed Description
Definition at line 29 of file IGrammarSimpleElement.java.
Member Function Documentation
get()
<N> N de.flashpixx.rrd_antlr4.antlr.IGrammarSimpleElement< T >.get ()
Returns
value
Template Parameters
N any casting type
Implemented in de.flashpixx.rrd_antlr4.antlr.CGrammarTerminalValue< T >.
Referenced by de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.nonterminal(), de.flashpixx.rrd_antlr4.engine.template.CHTML.nonterminal(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.terminalvalue(), and de.flashpixx.rrd_antlr4.engine.template.CHTML.terminalvalue().
isValueAssignableTo()
boolean de.flashpixx.rrd_antlr4.antlr.IGrammarSimpleElement< T >.isValueAssignableTo (final Class<?>... p_class)
Parameters
p_class class
Returns
assignable (on null always true)
Implemented in de.flashpixx.rrd_antlr4.antlr.CGrammarTerminalValue< T >.