RRD-ANTLR4: de.flashpixx.rrd_antlr4.IBaseTest Class Reference
de.flashpixx.rrd_antlr4.IBaseTest Class Reference abstract
base test class with helpers
Protected Member Functions
final void invoketest ()
invoke all test manually
Private Member Functions
Set< Method > before ()
reads the before annotated methods
void execute (final Method p_method, final Set< Method > p_before, final Object... p_arguments)
invokes the method within the current object context
void invoke (final Method p_method, final Set< Method > p_before)
invoke method and read if possible the data-provider
Detailed Description
Definition at line 43 of file IBaseTest.java.
Member Function Documentation
before()
Set<Method> de.flashpixx.rrd_antlr4.IBaseTest.before () private
Returns
optional before method
Definition at line 145 of file IBaseTest.java.
Referenced by de.flashpixx.rrd_antlr4.IBaseTest.invoketest().
execute()
void de.flashpixx.rrd_antlr4.IBaseTest.execute (final Method p_method, final Set< Method > p_before, final Object... p_arguments) private
Parameters
p_method method
p_before before method
p_arguments optional arguments
Definition at line 101 of file IBaseTest.java.
Referenced by de.flashpixx.rrd_antlr4.IBaseTest.invoke().
invoke()
void de.flashpixx.rrd_antlr4.IBaseTest.invoke (final Method p_method, final Set< Method > p_before) private
Parameters
p_method method
p_before before method
Definition at line 65 of file IBaseTest.java.
References de.flashpixx.rrd_antlr4.IBaseTest.execute().
Referenced by de.flashpixx.rrd_antlr4.IBaseTest.invoketest().
invoketest()
final void de.flashpixx.rrd_antlr4.IBaseTest.invoketest () protected
Definition at line 49 of file IBaseTest.java.
References de.flashpixx.rrd_antlr4.IBaseTest.before(), and de.flashpixx.rrd_antlr4.IBaseTest.invoke().
Referenced by de.flashpixx.rrd_antlr4.TestCLanguageLabels.main().