RRD-ANTLR4: de.flashpixx.rrd_antlr4.engine.template.ETemplate Enum Reference
de.flashpixx.rrd_antlr4.engine.template.ETemplate Enum Reference
enum for template creation
Public Member Functions
ITemplate generate ()
creates a new de.template
Public Attributes
HTML
Detailed Description
Definition at line 32 of file ETemplate.java.
Member Function Documentation
generate()
ITemplate de.flashpixx.rrd_antlr4.engine.template.ETemplate.generate ()
Returns
template
Definition at line 42 of file ETemplate.java.
References de.flashpixx.rrd_antlr4.CCommon.languagestring().
Referenced by de.flashpixx.rrd_antlr4.engine.CEngine.generate(), and de.flashpixx.rrd_antlr4.generator.CPlugin.processmessages().
Member Data Documentation
HTML
de.flashpixx.rrd_antlr4.engine.template.ETemplate.HTML
Definition at line 34 of file ETemplate.java.