RRD-ANTLR4: de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate Class Reference
de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate Class Reference abstract
base implementation
Public Member Functions
IBaseTemplate (final String p_name, final String p_index)
ctor
final String index ()
returns the index file
final String name ()
returns the name of the template
Public Member Functions inherited from de.flashpixx.rrd_antlr4.engine.template.ITemplate
IGrammarComplexElement element (final IGrammarComplexElement p_grammar, final IGrammarComplexElement p_element)
is called if any grammar element is completed
IGrammarComplexElement grammar (final IGrammarComplexElement p_grammar)
is called on the grammar definition
void postprocess (final Path p_output) throws IOException, URISyntaxException
postprocessing (after AST visiting)
void preprocess (final Path p_output) throws IOException, URISyntaxException
preprocessing (before AST visiting)
Protected Member Functions
abstract String cardinality (final IGrammarElement.ECardinality p_cardinality, final String p_element)
sets the cardinality
abstract String choice (final IGrammarChoice p_element)
creates a grammar choice
final void copy (final String p_templatefile, final Path p_output) throws IOException, URISyntaxException
copies files from the directory of the template to the output directory
abstract String group (final IGrammarGroup p_element)
crates a grammer group
String map (final IGrammarElement p_element)
calls the sub routines to format the lement
abstract String negation (final IGrammarElement p_element)
creates a negation structure
abstract String nonterminal (final IGrammarIdentifier p_element)
creates a non-terminal
final void replace (final File p_file, final String... p_replacepair) throws IOException
replaces the string within the file
String rule (final IGrammarRule p_element)
creates a rule
abstract String sequence (final IGrammarCollection p_element)
creates a grammar sequence
String terminal (final IGrammarTerminal p_element)
creates a terminal
abstract String terminalvalue (final IGrammarSimpleElement<?> p_element)
creates a terminal
Static Protected Member Functions
static String linkhash (final String p_value)
create a hash of a link
static String removequotes (final String p_string)
removing quotes if needed
Private Attributes
final String m_index
index file name
final String m_name
template name
Detailed Description
Definition at line 59 of file IBaseTemplate.java.
Constructor & Destructor Documentation
IBaseTemplate()
de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.IBaseTemplate (final String p_name, final String p_index)
Parameters
p_name template name
p_index index file
Definition at line 77 of file IBaseTemplate.java.
Member Function Documentation
cardinality()
abstract String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.cardinality (final IGrammarElement.ECardinality p_cardinality, final String p_element) abstract protected
Parameters
p_cardinality cardinality value
p_element inner string
Returns
string represenation
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.rule().
choice()
abstract String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.choice (final IGrammarChoice p_element) abstract protected
Parameters
p_element element list
Returns
string representation
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.rule().
copy()
final void de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.copy (final String p_templatefile, final Path p_output) throws IOException, URISyntaxException protected
Parameters
p_templatefile file within the template directory
p_output output directory
Exceptions
IOException on IO error
URISyntaxException on URL syntax error
Definition at line 103 of file IBaseTemplate.java.
References de.flashpixx.rrd_antlr4.CCommon.resourceurl().
Referenced by de.flashpixx.rrd_antlr4.engine.template.CHTML.postprocess(), and de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.postprocess().
group()
abstract String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.group (final IGrammarGroup p_element) abstract protected
Parameters
p_element group element
Returns
string representation
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.rule().
index()
final String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.index ()
Returns
index file name without path
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 84 of file IBaseTemplate.java.
References de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.m_index.
linkhash()
static String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.linkhash (final String p_value) static protected
Parameters
p_value ID element
Returns
hash
Definition at line 188 of file IBaseTemplate.java.
Referenced by de.flashpixx.rrd_antlr4.engine.template.CHTML.element(), de.flashpixx.rrd_antlr4.engine.template.CHTML.nonterminal(), de.flashpixx.rrd_antlr4.engine.template.CHTML.postprocess(), and de.flashpixx.rrd_antlr4.engine.template.CHTML.terminalvalue().
map()
String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map (final IGrammarElement p_element) protected
Parameters
p_element grammat element or string
Returns
string representation
Definition at line 139 of file IBaseTemplate.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarElement.cardinality(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.cardinality(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.choice(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.group(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.negation(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.nonterminal(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.rule(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.sequence(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.terminal(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.terminalvalue().
Referenced by de.flashpixx.rrd_antlr4.engine.template.CHTML.choice(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.element(), de.flashpixx.rrd_antlr4.engine.template.CHTML.element(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.group(), de.flashpixx.rrd_antlr4.engine.template.CHTML.group(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.negation(), de.flashpixx.rrd_antlr4.engine.template.CHTML.negation(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.rule(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.terminal().
name()
final String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.name ()
Returns
template name
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 90 of file IBaseTemplate.java.
References de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.m_name.
negation()
abstract String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.negation (final IGrammarElement p_element) abstract protected
Parameters
p_element inner negation element
Returns
string represenation
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.terminal().
nonterminal()
abstract String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.nonterminal (final IGrammarIdentifier p_element) abstract protected
Parameters
p_element identifier element
Returns
string represenation
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.terminal().
removequotes()
static String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.removequotes (final String p_string) static protected
Parameters
p_string input string
Returns
unquoted string
Definition at line 175 of file IBaseTemplate.java.
Referenced by de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.escapelatex(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.nonterminal(), de.flashpixx.rrd_antlr4.engine.template.CHTML.nonterminal(), and de.flashpixx.rrd_antlr4.engine.template.CHTML.terminalvalue().
replace()
final void de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.replace (final File p_file, final String... p_replacepair) throws IOException protected
Parameters
p_file file
p_replacepair string tupels for replacing
Definition at line 120 of file IBaseTemplate.java.
References de.flashpixx.rrd_antlr4.CCommon.languagestring().
Referenced by de.flashpixx.rrd_antlr4.engine.template.CHTML.postprocess(), and de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.postprocess().
rule()
String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.rule (final IGrammarRule p_element) protected
Parameters
p_element rule element
Returns
string represenation
Definition at line 206 of file IBaseTemplate.java.
References de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.cardinality(), de.flashpixx.rrd_antlr4.antlr.IGrammarRule.children(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.choice(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.group(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.sequence(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.terminalvalue().
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map().
sequence()
abstract String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.sequence (final IGrammarCollection p_element) abstract protected
Parameters
p_element element list
Returns
string representation
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.rule().
terminal()
String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.terminal (final IGrammarTerminal p_element) protected
Parameters
p_element terminal element
Returns
string represenation
Definition at line 258 of file IBaseTemplate.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarTerminal.children(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.negation(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.nonterminal().
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map().
terminalvalue()
abstract String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.terminalvalue (final IGrammarSimpleElement<?> p_element) abstract protected
Parameters
p_element terminal value element
Returns
string represenation
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.rule().
Member Data Documentation
m_index
final String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.m_index private
Definition at line 69 of file IBaseTemplate.java.
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.index().
m_name
final String de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.m_name private
Definition at line 65 of file IBaseTemplate.java.
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.name().