RRD-ANTLR4: de.flashpixx.rrd_antlr4.engine.CEngine Class Reference
de.flashpixx.rrd_antlr4.engine.CEngine Class Reference
template engine
Public Member Functions
Collection< String > generate (final File p_baseoutputdirectory, final File p_outputdirectory, final File p_grammar, final Set< String > p_docuclean, final Map< String, File > p_imports, final Set< ETemplate > p_templates) throws IOException
generator call
Private Member Functions
Collection< String > parse (final File p_grammar, final Set< String > p_docuclean, final Map< String, File > p_imports, final ITemplate p_template) throws IOException
runs parsing process with recursive descent of a grammar file
Detailed Description
Definition at line 52 of file CEngine.java.
Member Function Documentation
generate()
Collection<String> de.flashpixx.rrd_antlr4.engine.CEngine.generate (final File p_baseoutputdirectory, final File p_outputdirectory, final File p_grammar, final Set< String > p_docuclean, final Map< String, File > p_imports, final Set< ETemplate > p_templates) throws IOException
Parameters
p_baseoutputdirectory base output directory
p_outputdirectory output directory - relative to base output directory
p_grammar grammar input file
p_docuclean set with documentation clean regex
p_imports map with grammar imported grammar files
p_templates exporting templates
Returns
list with error messages
list with error messages
Exceptions
IOException on IO error
Definition at line 67 of file CEngine.java.
References de.flashpixx.rrd_antlr4.engine.template.ETemplate.generate(), de.flashpixx.rrd_antlr4.CCommon.outputdirectory(), and de.flashpixx.rrd_antlr4.engine.CEngine.parse().
Referenced by de.flashpixx.rrd_antlr4.generator.IBaseGenerator.generate().
parse()
Collection<String> de.flashpixx.rrd_antlr4.engine.CEngine.parse (final File p_grammar, final Set< String > p_docuclean, final Map< String, File > p_imports, final ITemplate p_template) throws IOException private
Parameters
p_grammar grammar file
p_docuclean set with documentation clean regex
p_imports map with grammar imported grammar files
p_template template which will be passend
Returns
colleciton with error messages
Exceptions
IOException thrown on IO errors
Definition at line 115 of file CEngine.java.
References de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.getGrammarImports().
Referenced by de.flashpixx.rrd_antlr4.engine.CEngine.generate().