RRD-ANTLR4: de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement Interface Reference
de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement Interface Reference
base interface of a complex grammar element
Public Member Functions
String documentation ()
documentation of the element
String id ()
ID of the element.
Public Member Functions inherited from de.flashpixx.rrd_antlr4.antlr.IGrammarElement
ECardinality cardinality ()
returns the cardinality
IGrammarElement cardinality (final ECardinality p_cardinality)
changes the cardinality
Detailed Description
Definition at line 29 of file IGrammarComplexElement.java.
Member Function Documentation
documentation()
String de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement.documentation ()
Returns
documentation
Implemented in de.flashpixx.rrd_antlr4.antlr.CGrammarNonTerminal, de.flashpixx.rrd_antlr4.antlr.CGrammarRule, and de.flashpixx.rrd_antlr4.antlr.CGrammar.
Referenced by de.flashpixx.rrd_antlr4.engine.template.CHTML.element(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.postprocess(), and de.flashpixx.rrd_antlr4.engine.template.CHTML.postprocess().
id()
String de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement.id ()
Returns
ID
Implemented in de.flashpixx.rrd_antlr4.antlr.CGrammarNonTerminal, de.flashpixx.rrd_antlr4.antlr.CGrammarRule, and de.flashpixx.rrd_antlr4.antlr.CGrammar.
Referenced by de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.element(), de.flashpixx.rrd_antlr4.engine.template.CHTML.element(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.postprocess(), and de.flashpixx.rrd_antlr4.engine.template.CHTML.postprocess().