RRD-ANTLR4: de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE Class Reference
de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE Class Reference
AntLR 4 AST visitor of perl regular expressions.
Inherits PCREBaseVisitor< Object >.
Public Member Functions
final Object visitAlternation (final PCREParser.AlternationContext p_context)
final Object visitAtom (final PCREParser.AtomContext p_context)
final Object visitCapture (final PCREParser.CaptureContext p_context)
final Object visitCharacter_class (final PCREParser.Character_classContext p_context)
final Object visitElement (final PCREParser.ElementContext p_context)
final Object visitExpr (final PCREParser.ExprContext p_context)
final Object visitParse (final PCREParser.ParseContext p_context)
Private Member Functions
int filter (final int p_start, final List< Pair<?, String >> p_list)
filters the pair list of string or quantifier
List< Pair<?, String > > implode (final List< Pair<?, String >> p_list)
implodes a list of any objects, strings will be concated into one string
IGrammarElement terminalvalue (final String p_string)
create a terminal value of a string
Detailed Description
Definition at line 41 of file CASTVisitorPCRE.java.
Member Function Documentation
filter()
int de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.filter (final int p_start, final List< Pair<?, String >> p_list) private
Parameters
p_start start index
p_list list
Returns
end position of a string or quantifier element, -1 on non found
Definition at line 216 of file CASTVisitorPCRE.java.
implode()
List<Pair<?, String> > de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.implode (final List< Pair<?, String >> p_list) private
Parameters
p_list list of pairs object & quantifier
Returns
list with concated objects and used quantifier
Definition at line 185 of file CASTVisitorPCRE.java.
References de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.implode().
Referenced by de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.implode().
terminalvalue()
IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.terminalvalue (final String p_string) private
Parameters
p_string string
Returns
grammar element
Note
the string can be a dot "." for "any character" or can start with "~" for negation
Definition at line 169 of file CASTVisitorPCRE.java.
References de.flashpixx.rrd_antlr4.CCommon.languagestring().
visitAlternation()
final Object de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitAlternation (final PCREParser.AlternationContext p_context)
Definition at line 145 of file CASTVisitorPCRE.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.choice().
visitAtom()
final Object de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitAtom (final PCREParser.AtomContext p_context)
Definition at line 61 of file CASTVisitorPCRE.java.
visitCapture()
final Object de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitCapture (final PCREParser.CaptureContext p_context)
Definition at line 45 of file CASTVisitorPCRE.java.
visitCharacter_class()
final Object de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitCharacter_class (final PCREParser.Character_classContext p_context)
Definition at line 51 of file CASTVisitorPCRE.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.choice().
visitElement()
final Object de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitElement (final PCREParser.ElementContext p_context)
Definition at line 88 of file CASTVisitorPCRE.java.
visitExpr()
final Object de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitExpr (final PCREParser.ExprContext p_context)
Definition at line 101 of file CASTVisitorPCRE.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.cardinality(), and de.flashpixx.rrd_antlr4.antlr.CCommon.sequence().
visitParse()
final Object de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitParse (final PCREParser.ParseContext p_context)
Definition at line 156 of file CASTVisitorPCRE.java.