RRD-ANTLR4: de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR Class Reference
de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR Class Reference
AntLR 4 AST visitor of AntLR 4 grammar file.
Inherits ANTLRv4ParserBaseVisitor< IGrammarElement >.
Public Member Functions
CASTVisitorAntLR (final ITemplate p_template, final Set< String > p_docuclean)
exporting template
final Set< IGrammarSimpleElement< String > > getGrammarImports ()
returns a set with grammar imports
final IGrammarElement visitAlternative (final ANTLRv4Parser.AlternativeContext p_context)
final IGrammarElement visitAltList (final ANTLRv4Parser.AltListContext p_context)
final IGrammarElement visitBlock (final ANTLRv4Parser.BlockContext p_context)
final IGrammarElement visitBlockSet (final ANTLRv4Parser.BlockSetContext p_context)
final IGrammarElement visitDelegateGrammar (final ANTLRv4Parser.DelegateGrammarContext p_context)
final IGrammarElement visitEbnf (final ANTLRv4Parser.EbnfContext p_context)
final IGrammarElement visitElement (final ANTLRv4Parser.ElementContext p_context)
final IGrammarElement visitGrammarSpec (final ANTLRv4Parser.GrammarSpecContext p_context)
final IGrammarElement visitId (final ANTLRv4Parser.IdContext p_context)
final IGrammarElement visitLexerAlt (final ANTLRv4Parser.LexerAltContext p_context)
final IGrammarElement visitLexerAltList (final ANTLRv4Parser.LexerAltListContext p_context)
final IGrammarElement visitLexerElement (final ANTLRv4Parser.LexerElementContext p_context)
final IGrammarElement visitLexerElements (final ANTLRv4Parser.LexerElementsContext p_context)
final IGrammarElement visitLexerRuleSpec (final ANTLRv4Parser.LexerRuleSpecContext p_context)
final IGrammarElement visitNotSet (final ANTLRv4Parser.NotSetContext p_context)
final IGrammarElement visitParserRuleSpec (final ANTLRv4Parser.ParserRuleSpecContext p_context)
final IGrammarElement visitRuleAltList (final ANTLRv4Parser.RuleAltListContext p_context)
final IGrammarElement visitRuleref (final ANTLRv4Parser.RulerefContext p_context)
final IGrammarElement visitTerminal (final ANTLRv4Parser.TerminalContext p_context)
Private Attributes
final Set< String > m_docuclean
set with documentation clean pattern
IGrammarComplexElement m_grammar
grammar name - is set by the first grammar rule
Set< IGrammarSimpleElement< String > > m_imports = new HashSet<>()
set with grammer imports
final ITemplate m_template
exporting template
Detailed Description
Definition at line 37 of file CASTVisitorAntLR.java.
Constructor & Destructor Documentation
CASTVisitorAntLR()
de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.CASTVisitorAntLR (final ITemplate p_template, final Set< String > p_docuclean)
Parameters
p_template template
p_docuclean set with regex for documentation cleanup
Definition at line 62 of file CASTVisitorAntLR.java.
Member Function Documentation
getGrammarImports()
final Set<IGrammarSimpleElement<String> > de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.getGrammarImports ()
Returns
set with grammar imports
Definition at line 279 of file CASTVisitorAntLR.java.
Referenced by de.flashpixx.rrd_antlr4.engine.CEngine.parse().
visitAlternative()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitAlternative (final ANTLRv4Parser.AlternativeContext p_context)
Definition at line 169 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.sequence().
visitAltList()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitAltList (final ANTLRv4Parser.AltListContext p_context)
Definition at line 151 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.choice().
visitBlock()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitBlock (final ANTLRv4Parser.BlockContext p_context)
Definition at line 236 of file CASTVisitorAntLR.java.
visitBlockSet()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitBlockSet (final ANTLRv4Parser.BlockSetContext p_context)
Definition at line 187 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.choice().
visitDelegateGrammar()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitDelegateGrammar (final ANTLRv4Parser.DelegateGrammarContext p_context)
Definition at line 84 of file CASTVisitorAntLR.java.
visitEbnf()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitEbnf (final ANTLRv4Parser.EbnfContext p_context)
Definition at line 225 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.cardinality().
visitElement()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitElement (final ANTLRv4Parser.ElementContext p_context)
Definition at line 198 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.cardinality().
visitGrammarSpec()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitGrammarSpec (final ANTLRv4Parser.GrammarSpecContext p_context)
Definition at line 70 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.cleanComment(), and de.flashpixx.rrd_antlr4.engine.template.ITemplate.grammar().
visitId()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitId (final ANTLRv4Parser.IdContext p_context)
Definition at line 267 of file CASTVisitorAntLR.java.
visitLexerAlt()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerAlt (final ANTLRv4Parser.LexerAltContext p_context)
Definition at line 180 of file CASTVisitorAntLR.java.
visitLexerAltList()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerAltList (final ANTLRv4Parser.LexerAltListContext p_context)
Definition at line 115 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.choice().
visitLexerElement()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerElement (final ANTLRv4Parser.LexerElementContext p_context)
Definition at line 255 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.terminalvalue().
visitLexerElements()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerElements (final ANTLRv4Parser.LexerElementsContext p_context)
Definition at line 126 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.sequence().
visitLexerRuleSpec()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerRuleSpec (final ANTLRv4Parser.LexerRuleSpecContext p_context)
Definition at line 137 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.cleanComment(), and de.flashpixx.rrd_antlr4.engine.template.ITemplate.element().
visitNotSet()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitNotSet (final ANTLRv4Parser.NotSetContext p_context)
Definition at line 162 of file CASTVisitorAntLR.java.
visitParserRuleSpec()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitParserRuleSpec (final ANTLRv4Parser.ParserRuleSpecContext p_context)
Definition at line 91 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.cleanComment(), and de.flashpixx.rrd_antlr4.engine.template.ITemplate.element().
visitRuleAltList()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitRuleAltList (final ANTLRv4Parser.RuleAltListContext p_context)
Definition at line 104 of file CASTVisitorAntLR.java.
References de.flashpixx.rrd_antlr4.antlr.CCommon.choice().
visitRuleref()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitRuleref (final ANTLRv4Parser.RulerefContext p_context)
Definition at line 261 of file CASTVisitorAntLR.java.
visitTerminal()
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitTerminal (final ANTLRv4Parser.TerminalContext p_context)
Definition at line 245 of file CASTVisitorAntLR.java.
Member Data Documentation
m_docuclean
final Set<String> de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.m_docuclean private
Definition at line 54 of file CASTVisitorAntLR.java.
m_grammar
IGrammarComplexElement de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.m_grammar private
Definition at line 46 of file CASTVisitorAntLR.java.
m_imports
Set<IGrammarSimpleElement<String> > de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.m_imports = new HashSet<>() private
Definition at line 50 of file CASTVisitorAntLR.java.
m_template
final ITemplate de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.m_template private
Definition at line 42 of file CASTVisitorAntLR.java.