RRD-ANTLR4: de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality Enum Reference
de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality Enum Reference
enum define cardinalities
Public Member Functions
ECardinality (final String p_text)
final String toString ()
Public Attributes
NONE =("")
ONEORMORE =("+")
OPTIONAL =("?")
ZEROORMORE =("*")
Private Attributes
String m_text
string definition
Detailed Description
Definition at line 49 of file IGrammarElement.java.
Constructor & Destructor Documentation
ECardinality()
de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.ECardinality (final String p_text)
Definition at line 61 of file IGrammarElement.java.
Member Function Documentation
toString()
final String de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.toString ()
Definition at line 68 of file IGrammarElement.java.
Member Data Documentation
m_text
String de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.m_text private
Definition at line 59 of file IGrammarElement.java.
NONE
de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.NONE =("")
Definition at line 51 of file IGrammarElement.java.
Referenced by de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.cardinality(), de.flashpixx.rrd_antlr4.antlr.CGrammar.cardinality(), de.flashpixx.rrd_antlr4.antlr.CGrammarRule.cardinality(), de.flashpixx.rrd_antlr4.antlr.CGrammarChoice.CGrammarChoice(), de.flashpixx.rrd_antlr4.antlr.CGrammarGroup.CGrammarGroup(), de.flashpixx.rrd_antlr4.antlr.CGrammarNegation.CGrammarNegation(), de.flashpixx.rrd_antlr4.antlr.CGrammarNonTerminal.CGrammarNonTerminal(), and de.flashpixx.rrd_antlr4.antlr.CGrammarSequence.CGrammarSequence().
ONEORMORE
de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.ONEORMORE =("+")
Definition at line 54 of file IGrammarElement.java.
Referenced by de.flashpixx.rrd_antlr4.antlr.CCommon.cardinality().
OPTIONAL
de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.OPTIONAL =("?")
Definition at line 52 of file IGrammarElement.java.
Referenced by de.flashpixx.rrd_antlr4.antlr.CCommon.cardinality().
ZEROORMORE
de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.ZEROORMORE =("*")
Definition at line 53 of file IGrammarElement.java.
Referenced by de.flashpixx.rrd_antlr4.antlr.CCommon.cardinality().