RRD-ANTLR4: de.flashpixx.rrd_antlr4.antlr.IGrammarCollection Interface Reference
de.flashpixx.rrd_antlr4.antlr.IGrammarCollection Interface Reference
interface of grammar collection elements
Public Member Functions
List< IGrammarElement > get ()
returns the elements
Public Member Functions inherited from de.flashpixx.rrd_antlr4.antlr.IGrammarElement
ECardinality cardinality ()
returns the cardinality
IGrammarElement cardinality (final ECardinality p_cardinality)
changes the cardinality
Detailed Description
Definition at line 31 of file IGrammarCollection.java.
Member Function Documentation
get()
List<IGrammarElement> de.flashpixx.rrd_antlr4.antlr.IGrammarCollection.get ()
Returns
collection of grammar elements
Implemented in de.flashpixx.rrd_antlr4.antlr.IGrammarBaseCollection, and de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.
Referenced by de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.choice(), de.flashpixx.rrd_antlr4.engine.template.CHTML.choice(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.sequence(), and de.flashpixx.rrd_antlr4.engine.template.CHTML.sequence().