RRD-ANTLR4: de.flashpixx.rrd_antlr4.CCommon Class Reference
de.flashpixx.rrd_antlr4.CCommon Class Reference
class for any helper calls
Classes
class CUTF8Control
class to read UTF-8 encoded property file
Static Public Member Functions
static void language (final Locale p_language)
sets the language
static String [] languages ()
list of usable languages
static< T > String languagestring (final T p_source, final String p_label, final Object... p_parameter)
returns the language depend string on any object
static String languagestring (final Class<?> p_class, final String p_label, final Object... p_parameter)
returns a string of the resource file
static Path outputdirectory (final File p_baseoutputdirectory, final ITemplate p_template, final File p_outputdirectory, final String... p_extension)
generates the full output directory
static URL resourceurl (final String p_file) throws URISyntaxException, MalformedURLException
returns a file from a resource e.g.
static URL resourceurl (final File p_file) throws URISyntaxException, MalformedURLException
returns a file from a resource e.g.
Static Public Attributes
static final String PACKAGEROOT = "de.flashpixx.rrd_antlr4"
package name
Static Package Functions
static URL concaturl (final URL p_base, final String p_string) throws MalformedURLException, URISyntaxException
concats an URL with a path
static ResourceBundle configuration ()
returns the property data of the package
static ResourceBundle languagebundle ()
returns the language bundle
static URL resourceurl ()
returns root path of the resource
Private Member Functions
CCommon ()
ctor - avoid instantiation
Static Private Member Functions
static String getLanguageLabel (final Class<?> p_class, final String p_label)
returns the label of a class and string to get access to the resource
Static Private Attributes
static final ResourceBundle PROPERTIES
properties of the package
static ResourceBundle s_language
language resource bundle
Detailed Description
Definition at line 51 of file CCommon.java.
Constructor & Destructor Documentation
CCommon()
de.flashpixx.rrd_antlr4.CCommon.CCommon () private
Definition at line 77 of file CCommon.java.
Member Function Documentation
concaturl()
static URL de.flashpixx.rrd_antlr4.CCommon.concaturl (final URL p_base, final String p_string) throws MalformedURLException, URISyntaxException static package
Parameters
p_base base URL
p_string additional path
Returns
new URL
Exceptions
URISyntaxException thrown on syntax error
MalformedURLException thrown on malformat
Definition at line 135 of file CCommon.java.
configuration()
static ResourceBundle de.flashpixx.rrd_antlr4.CCommon.configuration () static package
Returns
property object
Definition at line 120 of file CCommon.java.
References de.flashpixx.rrd_antlr4.CCommon.PROPERTIES.
Referenced by de.flashpixx.rrd_antlr4.TestCLanguageLabels.testTranslation().
getLanguageLabel()
static String de.flashpixx.rrd_antlr4.CCommon.getLanguageLabel (final Class<?> p_class, final String p_label) static private
Parameters
p_class class for static calls
p_label label name of the object
Returns
label name
Definition at line 227 of file CCommon.java.
Referenced by de.flashpixx.rrd_antlr4.CCommon.languagestring().
language()
static void de.flashpixx.rrd_antlr4.CCommon.language (final Locale p_language) static
Parameters
p_language language
Definition at line 85 of file CCommon.java.
languagebundle()
static ResourceBundle de.flashpixx.rrd_antlr4.CCommon.languagebundle () static package
Returns
bundle
Definition at line 110 of file CCommon.java.
References de.flashpixx.rrd_antlr4.CCommon.s_language.
languages()
static String [] de.flashpixx.rrd_antlr4.CCommon.languages () static
Returns
list of language pattern
Definition at line 100 of file CCommon.java.
languagestring() [1/2]
static <T> String de.flashpixx.rrd_antlr4.CCommon.languagestring (final T p_source, final String p_label, final Object... p_parameter) static
Parameters
p_source any object
p_label label name
p_parameter parameter
Returns
translated string
Template Parameters
T object type
Definition at line 195 of file CCommon.java.
Referenced by de.flashpixx.rrd_antlr4.engine.template.ETemplate.generate(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.negation(), de.flashpixx.rrd_antlr4.engine.template.CHTML.negation(), de.flashpixx.rrd_antlr4.engine.template.CHTML.postprocess(), de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.postprocess(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.replace(), de.flashpixx.rrd_antlr4.CCommon.resourceurl(), and de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.terminalvalue().
languagestring() [2/2]
static String de.flashpixx.rrd_antlr4.CCommon.languagestring (final Class<?> p_class, final String p_label, final Object... p_parameter) static
Parameters
p_class class for static calls
p_label label name of the object
p_parameter object array with substitutions
Returns
resource string
Definition at line 208 of file CCommon.java.
References de.flashpixx.rrd_antlr4.CCommon.getLanguageLabel().
outputdirectory()
static Path de.flashpixx.rrd_antlr4.CCommon.outputdirectory (final File p_baseoutputdirectory, final ITemplate p_template, final File p_outputdirectory, final String... p_extension) static
Parameters
p_baseoutputdirectory base output directory
p_template exporting template
p_outputdirectory relative output directory
p_extension optional path extension
Returns
full path
Definition at line 242 of file CCommon.java.
References de.flashpixx.rrd_antlr4.engine.template.ITemplate.name().
Referenced by de.flashpixx.rrd_antlr4.engine.CEngine.generate(), and de.flashpixx.rrd_antlr4.generator.CPlugin.processmessages().
resourceurl() [1/3]
static URL de.flashpixx.rrd_antlr4.CCommon.resourceurl () static package
Returns
URL of file or null
Definition at line 145 of file CCommon.java.
Referenced by de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.copy(), and de.flashpixx.rrd_antlr4.CCommon.resourceurl().
resourceurl() [2/3]
static URL de.flashpixx.rrd_antlr4.CCommon.resourceurl (final String p_file) throws URISyntaxException, MalformedURLException static
Jar file
Parameters
p_file file
Returns
URL of file or null
Exceptions
URISyntaxException thrown on syntax error
MalformedURLException thrown on malformat
Definition at line 159 of file CCommon.java.
References de.flashpixx.rrd_antlr4.CCommon.resourceurl().
resourceurl() [3/3]
static URL de.flashpixx.rrd_antlr4.CCommon.resourceurl (final File p_file) throws URISyntaxException, MalformedURLException static
Jar file
Parameters
p_file file relative to the CMain
Returns
URL of file or null
Exceptions
URISyntaxException is thrown on URI errors
MalformedURLException is thrown on malformat
Definition at line 173 of file CCommon.java.
References de.flashpixx.rrd_antlr4.CCommon.languagestring().
Member Data Documentation
PACKAGEROOT
final String de.flashpixx.rrd_antlr4.CCommon.PACKAGEROOT = "de.flashpixx.rrd_antlr4" static
Definition at line 56 of file CCommon.java.
Referenced by de.flashpixx.rrd_antlr4.TestCLanguageLabels.CJavaVistor.label(), and de.flashpixx.rrd_antlr4.TestCLanguageLabels.testResourceString().
PROPERTIES
final ResourceBundle de.flashpixx.rrd_antlr4.CCommon.PROPERTIES static private
Initial value:
= ResourceBundle.getBundle(
            MessageFormat.format( "{0}.{1}", PACKAGEROOT, "configuration" ),
            Locale.getDefault(),
            new CUTF8Control()
    )
Definition at line 60 of file CCommon.java.
Referenced by de.flashpixx.rrd_antlr4.CCommon.configuration().
s_language
ResourceBundle de.flashpixx.rrd_antlr4.CCommon.s_language static private
Initial value:
= ResourceBundle.getBundle(
            MessageFormat.format( "{0}.{1}", PACKAGEROOT, "language" ),
            Locale.getDefault(),
            new CUTF8Control()
    )
Definition at line 68 of file CCommon.java.
Referenced by de.flashpixx.rrd_antlr4.CCommon.languagebundle().