RRD-ANTLR4: de.flashpixx.rrd_antlr4.generator.IBaseGenerator Class Reference
de.flashpixx.rrd_antlr4.generator.IBaseGenerator Class Reference abstract
base generator class with default definitions
Public Member Functions
IGenerator finish ()
finishing after all grammar files are proceed
final IGenerator generate (final File p_grammar)
generates export for a grammar file
final boolean hasError ()
boolean error flag
Protected Member Functions
IBaseGenerator (final File p_baseoutputdirectory, final Set< File > p_imports, final Set< String > p_docuclean, final Set< ETemplate > p_templates)
ctor
abstract IGenerator processmessages (final File p_grammar, final File p_outputdirectory, final Collection< String > p_messages)
processes the error messages
abstract File processoutputdirectory (final File p_grammar)
processes the output directory
Protected Attributes
final File m_baseoutput
base output directory
boolean m_error
result generator error
final Set< ETemplate > m_templates
set of generator templates
Private Attributes
final Set< String > m_docuclean
set with regex string for documentation cleaning
final Map< String, File > m_imports
map with imported grammar files
Static Private Attributes
static final CEngine ENGINE = new CEngine()
engine instance
Detailed Description
Definition at line 43 of file IBaseGenerator.java.
Constructor & Destructor Documentation
IBaseGenerator()
de.flashpixx.rrd_antlr4.generator.IBaseGenerator.IBaseGenerator (final File p_baseoutputdirectory, final Set< File > p_imports, final Set< String > p_docuclean, final Set< ETemplate > p_templates) protected
Parameters
p_baseoutputdirectory base output directory
p_templates array with exporting templates
p_imports set with imported grammar files
p_docuclean set with documentation strings
Definition at line 79 of file IBaseGenerator.java.
Member Function Documentation
finish()
IGenerator de.flashpixx.rrd_antlr4.generator.IBaseGenerator.finish ()
Returns
generator self reference
Implements de.flashpixx.rrd_antlr4.generator.IGenerator.
Definition at line 120 of file IBaseGenerator.java.
References de.flashpixx.rrd_antlr4.generator.IBaseGenerator.processmessages(), and de.flashpixx.rrd_antlr4.generator.IBaseGenerator.processoutputdirectory().
generate()
final IGenerator de.flashpixx.rrd_antlr4.generator.IBaseGenerator.generate (final File p_grammar)
Parameters
p_grammar grammar file
Returns
generator self reference
Implements de.flashpixx.rrd_antlr4.generator.IGenerator.
Definition at line 89 of file IBaseGenerator.java.
References de.flashpixx.rrd_antlr4.engine.CEngine.generate(), de.flashpixx.rrd_antlr4.generator.IBaseGenerator.processmessages(), and de.flashpixx.rrd_antlr4.generator.IBaseGenerator.processoutputdirectory().
hasError()
final boolean de.flashpixx.rrd_antlr4.generator.IBaseGenerator.hasError ()
Returns
flag of errors
Implements de.flashpixx.rrd_antlr4.generator.IGenerator.
Definition at line 114 of file IBaseGenerator.java.
References de.flashpixx.rrd_antlr4.generator.IBaseGenerator.m_error.
processmessages()
abstract IGenerator de.flashpixx.rrd_antlr4.generator.IBaseGenerator.processmessages (final File p_grammar, final File p_outputdirectory, final Collection< String > p_messages) abstract protected
Parameters
p_grammar input grammar file
p_outputdirectory output directory
p_messages error messages
Returns
generator self reference
Referenced by de.flashpixx.rrd_antlr4.generator.IBaseGenerator.finish(), and de.flashpixx.rrd_antlr4.generator.IBaseGenerator.generate().
processoutputdirectory()
abstract File de.flashpixx.rrd_antlr4.generator.IBaseGenerator.processoutputdirectory (final File p_grammar) abstract protected
Parameters
p_grammar input grammar file
Returns
new output directory
Referenced by de.flashpixx.rrd_antlr4.generator.IBaseGenerator.finish(), and de.flashpixx.rrd_antlr4.generator.IBaseGenerator.generate().
Member Data Documentation
ENGINE
final CEngine de.flashpixx.rrd_antlr4.generator.IBaseGenerator.ENGINE = new CEngine() static private
Definition at line 48 of file IBaseGenerator.java.
m_baseoutput
final File de.flashpixx.rrd_antlr4.generator.IBaseGenerator.m_baseoutput protected
Definition at line 60 of file IBaseGenerator.java.
Referenced by de.flashpixx.rrd_antlr4.generator.CPlugin.processmessages().
m_docuclean
final Set<String> de.flashpixx.rrd_antlr4.generator.IBaseGenerator.m_docuclean private
Definition at line 68 of file IBaseGenerator.java.
m_error
boolean de.flashpixx.rrd_antlr4.generator.IBaseGenerator.m_error protected
Definition at line 52 of file IBaseGenerator.java.
Referenced by de.flashpixx.rrd_antlr4.generator.CPlugin.finish(), de.flashpixx.rrd_antlr4.generator.IBaseGenerator.hasError(), de.flashpixx.rrd_antlr4.generator.CStandalone.processmessages(), and de.flashpixx.rrd_antlr4.generator.CPlugin.processmessages().
m_imports
final Map<String, File> de.flashpixx.rrd_antlr4.generator.IBaseGenerator.m_imports private
Definition at line 64 of file IBaseGenerator.java.
m_templates
final Set<ETemplate> de.flashpixx.rrd_antlr4.generator.IBaseGenerator.m_templates protected
Definition at line 56 of file IBaseGenerator.java.
Referenced by de.flashpixx.rrd_antlr4.generator.CPlugin.processmessages(), and de.flashpixx.rrd_antlr4.generator.CPlugin.CReportGenerator.renderBody().