RRD-ANTLR4: de.flashpixx.rrd_antlr4.antlr.CCommon Class Reference
de.flashpixx.rrd_antlr4.antlr.CCommon Class Reference
grammar functions
Static Public Member Functions
static IGrammarElement cardinality (final String p_cardinality, final IGrammarElement p_element)
defines the cardinality of an grammar element
static IGrammarElement choice (final List< IGrammarElement > p_elements)
creates a choice
static String cleanComment (final String p_comment, final Set< String > p_docuclean)
cleanup comment from doxygen structure
static String cleanString (final String p_string)
clean string value
static IGrammarElement sequence (final List< IGrammarElement > p_elements)
creates a sequence
static IGrammarElement terminalvalue (final String p_value)
generates a terminal element with data
Private Member Functions
CCommon ()
ctor
Detailed Description
Definition at line 41 of file antlr/CCommon.java.
Constructor & Destructor Documentation
CCommon()
de.flashpixx.rrd_antlr4.antlr.CCommon.CCommon () private
Definition at line 47 of file antlr/CCommon.java.
Member Function Documentation
cardinality()
static IGrammarElement de.flashpixx.rrd_antlr4.antlr.CCommon.cardinality (final String p_cardinality, final IGrammarElement p_element) static
Parameters
p_cardinality cardinality string
p_element element
Returns
modified element
Definition at line 98 of file antlr/CCommon.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarElement.cardinality(), de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.ONEORMORE, de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.OPTIONAL, and de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.ZEROORMORE.
Referenced by de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitEbnf(), de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitElement(), and de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitExpr().
choice()
static IGrammarElement de.flashpixx.rrd_antlr4.antlr.CCommon.choice (final List< IGrammarElement > p_elements) static
Parameters
p_elements grammar elements
Returns
grammar element
Definition at line 71 of file antlr/CCommon.java.
Referenced by de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitAlternation(), de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitAltList(), de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitBlockSet(), de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitCharacter_class(), de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerAltList(), and de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitRuleAltList().
cleanComment()
static String de.flashpixx.rrd_antlr4.antlr.CCommon.cleanComment (final String p_comment, final Set< String > p_docuclean) static
Parameters
p_comment comment input
p_docuclean set with regular expression for cleaning
Returns
cleaned text or null
Definition at line 154 of file antlr/CCommon.java.
References de.flashpixx.rrd_antlr4.CStringReplace.get(), de.flashpixx.rrd_antlr4.CStringReplace.replace(), and de.flashpixx.rrd_antlr4.CStringReplace.replaceAll().
Referenced by de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitGrammarSpec(), de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerRuleSpec(), and de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitParserRuleSpec().
cleanString()
static String de.flashpixx.rrd_antlr4.antlr.CCommon.cleanString (final String p_string) static
Parameters
p_string string data
Returns
cleaned string
Definition at line 57 of file antlr/CCommon.java.
sequence()
static IGrammarElement de.flashpixx.rrd_antlr4.antlr.CCommon.sequence (final List< IGrammarElement > p_elements) static
Parameters
p_elements grammar elements
Returns
grammar element
Definition at line 84 of file antlr/CCommon.java.
Referenced by de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitAlternative(), de.flashpixx.rrd_antlr4.antlr.CASTVisitorPCRE.visitExpr(), and de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerElements().
terminalvalue()
static IGrammarElement de.flashpixx.rrd_antlr4.antlr.CCommon.terminalvalue (final String p_value) static
Parameters
p_value data string
Returns
grammar terminal element
Definition at line 119 of file antlr/CCommon.java.
Referenced by de.flashpixx.rrd_antlr4.antlr.CASTVisitorAntLR.visitLexerElement().