RRD-ANTLR4: de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection Class Reference
de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection Class Reference
empty grammar collection
Public Member Functions
final ECardinality cardinality ()
returns the cardinality
final IGrammarElement cardinality (final ECardinality p_cardinality)
changes the cardinality
final boolean equals (final Object p_object)
final List< IGrammarElement > get ()
returns the elements
final int hashCode ()
final String toString ()
Private Member Functions
CGrammarEmptyCollection ()
ctor
Static Private Attributes
static final CGrammarEmptyCollection INSTANCE = new CGrammarEmptyCollection()
singletone instance
Detailed Description
Definition at line 33 of file CGrammarEmptyCollection.java.
Constructor & Destructor Documentation
CGrammarEmptyCollection()
de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.CGrammarEmptyCollection () private
Definition at line 44 of file CGrammarEmptyCollection.java.
Member Function Documentation
cardinality() [1/2]
final ECardinality de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.cardinality ()
Returns
cardinality
Implements de.flashpixx.rrd_antlr4.antlr.IGrammarElement.
Definition at line 55 of file CGrammarEmptyCollection.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarElement.ECardinality.NONE.
cardinality() [2/2]
final IGrammarElement de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.cardinality (final ECardinality p_cardinality)
Parameters
p_cardinality cardinality value
Returns
self reference
Implements de.flashpixx.rrd_antlr4.antlr.IGrammarElement.
Definition at line 61 of file CGrammarEmptyCollection.java.
equals()
final boolean de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.equals (final Object p_object)
Definition at line 73 of file CGrammarEmptyCollection.java.
References de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.hashCode().
get()
final List<IGrammarElement> de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.get ()
Returns
collection of grammar elements
Implements de.flashpixx.rrd_antlr4.antlr.IGrammarCollection.
Definition at line 49 of file CGrammarEmptyCollection.java.
hashCode()
final int de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.hashCode ()
Definition at line 67 of file CGrammarEmptyCollection.java.
References de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.hashCode().
Referenced by de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.equals(), and de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.hashCode().
toString()
final String de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.toString ()
Definition at line 79 of file CGrammarEmptyCollection.java.
Member Data Documentation
INSTANCE
final CGrammarEmptyCollection de.flashpixx.rrd_antlr4.antlr.CGrammarEmptyCollection.INSTANCE = new CGrammarEmptyCollection() static private
Definition at line 38 of file CGrammarEmptyCollection.java.