RRD-ANTLR4: de.flashpixx.rrd_antlr4.CStringReplace Class Reference
de.flashpixx.rrd_antlr4.CStringReplace Class Reference
class for replacing string content
Public Member Functions
CStringReplace (final String p_data)
ctor
final boolean equals (final Object p_object)
final String get ()
returns the data
final int hashCode ()
final CStringReplace replace (final CharSequence p_search, final CharSequence p_replace)
replace a char sequence
final CStringReplace replaceAll (final String p_search, final String p_replace)
replaces the content
final String toString ()
Private Attributes
String m_data
string data
Detailed Description
Definition at line 32 of file CStringReplace.java.
Constructor & Destructor Documentation
CStringReplace()
de.flashpixx.rrd_antlr4.CStringReplace.CStringReplace (final String p_data)
Parameters
p_data input data
Definition at line 44 of file CStringReplace.java.
Referenced by de.flashpixx.rrd_antlr4.CStringReplace.equals().
Member Function Documentation
equals()
final boolean de.flashpixx.rrd_antlr4.CStringReplace.equals (final Object p_object)
Definition at line 92 of file CStringReplace.java.
References de.flashpixx.rrd_antlr4.CStringReplace.CStringReplace().
get()
final String de.flashpixx.rrd_antlr4.CStringReplace.get ()
Returns
string
Definition at line 80 of file CStringReplace.java.
References de.flashpixx.rrd_antlr4.CStringReplace.m_data.
Referenced by de.flashpixx.rrd_antlr4.antlr.CCommon.cleanComment().
hashCode()
final int de.flashpixx.rrd_antlr4.CStringReplace.hashCode ()
Definition at line 86 of file CStringReplace.java.
replace()
final CStringReplace de.flashpixx.rrd_antlr4.CStringReplace.replace (final CharSequence p_search, final CharSequence p_replace)
Parameters
p_search search char sequence
p_replace replace char sequence
Returns
object reference
Definition at line 69 of file CStringReplace.java.
References de.flashpixx.rrd_antlr4.CStringReplace.replace().
Referenced by de.flashpixx.rrd_antlr4.antlr.CCommon.cleanComment(), and de.flashpixx.rrd_antlr4.CStringReplace.replace().
replaceAll()
final CStringReplace de.flashpixx.rrd_antlr4.CStringReplace.replaceAll (final String p_search, final String p_replace)
Parameters
p_search source
p_replace target
Returns
object reference
Definition at line 56 of file CStringReplace.java.
References de.flashpixx.rrd_antlr4.CStringReplace.replaceAll().
Referenced by de.flashpixx.rrd_antlr4.antlr.CCommon.cleanComment(), and de.flashpixx.rrd_antlr4.CStringReplace.replaceAll().
toString()
final String de.flashpixx.rrd_antlr4.CStringReplace.toString ()
Definition at line 98 of file CStringReplace.java.
References de.flashpixx.rrd_antlr4.CStringReplace.m_data.
Member Data Documentation
m_data
String de.flashpixx.rrd_antlr4.CStringReplace.m_data private
Definition at line 37 of file CStringReplace.java.
Referenced by de.flashpixx.rrd_antlr4.CStringReplace.get(), and de.flashpixx.rrd_antlr4.CStringReplace.toString().