RRD-ANTLR4: de.flashpixx.rrd_antlr4.engine.template.CHTML Class Reference
de.flashpixx.rrd_antlr4.engine.template.CHTML Class Reference
template for HTML export
Public Member Functions
final IGrammarComplexElement element (final IGrammarComplexElement p_grammar, final IGrammarComplexElement p_element)
is called if any grammar element is completed
final IGrammarComplexElement grammar (final IGrammarComplexElement p_grammar)
is called on the grammar definition
final void postprocess (final Path p_output) throws IOException, URISyntaxException
postprocessing (after AST visiting)
final void preprocess (final Path p_output) throws IOException, URISyntaxException
preprocessing (before AST visiting)
Public Member Functions inherited from de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate
IBaseTemplate (final String p_name, final String p_index)
ctor
final String index ()
returns the index file
final String name ()
returns the name of the template
Protected Member Functions
final String cardinality (final IGrammarElement.ECardinality p_cardinality, final String p_element)
final String choice (final IGrammarChoice p_element)
final String group (final IGrammarGroup p_element)
final String negation (final IGrammarElement p_element)
final String nonterminal (final IGrammarIdentifier p_element)
final String sequence (final IGrammarCollection p_element)
final String terminalvalue (final IGrammarSimpleElement<?> p_element)
Protected Member Functions inherited from de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate
abstract String cardinality (final IGrammarElement.ECardinality p_cardinality, final String p_element)
sets the cardinality
abstract String choice (final IGrammarChoice p_element)
creates a grammar choice
final void copy (final String p_templatefile, final Path p_output) throws IOException, URISyntaxException
copies files from the directory of the template to the output directory
abstract String group (final IGrammarGroup p_element)
crates a grammer group
String map (final IGrammarElement p_element)
calls the sub routines to format the lement
abstract String negation (final IGrammarElement p_element)
creates a negation structure
abstract String nonterminal (final IGrammarIdentifier p_element)
creates a non-terminal
final void replace (final File p_file, final String... p_replacepair) throws IOException
replaces the string within the file
String rule (final IGrammarRule p_element)
creates a rule
abstract String sequence (final IGrammarCollection p_element)
creates a grammar sequence
String terminal (final IGrammarTerminal p_element)
creates a terminal
abstract String terminalvalue (final IGrammarSimpleElement<?> p_element)
creates a terminal
Package Functions
CHTML (final String p_name)
ctor
Private Attributes
IGrammarComplexElement m_grammar
main grammar
final Table< String, String, String > m_rules = HashBasedTable.create()
rules table
Additional Inherited Members
Static Protected Member Functions inherited from de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate
static String linkhash (final String p_value)
create a hash of a link
static String removequotes (final String p_string)
removing quotes if needed
Detailed Description
Definition at line 54 of file CHTML.java.
Constructor & Destructor Documentation
CHTML()
de.flashpixx.rrd_antlr4.engine.template.CHTML.CHTML (final String p_name) package
Parameters
p_name template name
Definition at line 70 of file CHTML.java.
Member Function Documentation
cardinality()
final String de.flashpixx.rrd_antlr4.engine.template.CHTML.cardinality (final IGrammarElement.ECardinality p_cardinality, final String p_element) protected
Definition at line 261 of file CHTML.java.
choice()
final String de.flashpixx.rrd_antlr4.engine.template.CHTML.choice (final IGrammarChoice p_element) protected
Definition at line 201 of file CHTML.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarCollection.get(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map().
element()
final IGrammarComplexElement de.flashpixx.rrd_antlr4.engine.template.CHTML.element (final IGrammarComplexElement p_grammar, final IGrammarComplexElement p_element)
Parameters
p_grammar grammar
p_element element
Returns
grammar object reference
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 166 of file CHTML.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement.documentation(), de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement.id(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.linkhash(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map().
grammar()
final IGrammarComplexElement de.flashpixx.rrd_antlr4.engine.template.CHTML.grammar (final IGrammarComplexElement p_grammar)
Parameters
p_grammar grammar
Returns
grammar object reference
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 156 of file CHTML.java.
group()
final String de.flashpixx.rrd_antlr4.engine.template.CHTML.group (final IGrammarGroup p_element) protected
Definition at line 195 of file CHTML.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarGroup.element(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map().
negation()
final String de.flashpixx.rrd_antlr4.engine.template.CHTML.negation (final IGrammarElement p_element) protected
Definition at line 251 of file CHTML.java.
References de.flashpixx.rrd_antlr4.CCommon.languagestring(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map().
nonterminal()
final String de.flashpixx.rrd_antlr4.engine.template.CHTML.nonterminal (final IGrammarIdentifier p_element) protected
Definition at line 241 of file CHTML.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarSimpleElement< T >.get(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.linkhash(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.removequotes().
postprocess()
final void de.flashpixx.rrd_antlr4.engine.template.CHTML.postprocess (final Path p_output) throws IOException, URISyntaxException
Parameters
p_output working directory
Exceptions
IOException on io errors
URISyntaxException on uri syntax
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 81 of file CHTML.java.
References de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.copy(), de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement.documentation(), de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement.id(), de.flashpixx.rrd_antlr4.CCommon.languagestring(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.linkhash(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.replace().
preprocess()
final void de.flashpixx.rrd_antlr4.engine.template.CHTML.preprocess (final Path p_output) throws IOException, URISyntaxException
Parameters
p_output output directory
Exceptions
IOException on io errors
URISyntaxException on uri syntax
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 76 of file CHTML.java.
sequence()
final String de.flashpixx.rrd_antlr4.engine.template.CHTML.sequence (final IGrammarCollection p_element) protected
Definition at line 217 of file CHTML.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarCollection.get().
terminalvalue()
final String de.flashpixx.rrd_antlr4.engine.template.CHTML.terminalvalue (final IGrammarSimpleElement<?> p_element) protected
Definition at line 231 of file CHTML.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarSimpleElement< T >.get(), de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.linkhash(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.removequotes().
Member Data Documentation
m_grammar
IGrammarComplexElement de.flashpixx.rrd_antlr4.engine.template.CHTML.m_grammar private
Definition at line 59 of file CHTML.java.
m_rules
final Table<String, String, String> de.flashpixx.rrd_antlr4.engine.template.CHTML.m_rules = HashBasedTable.create() private
Definition at line 63 of file CHTML.java.