RRD-ANTLR4: de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax Class Reference
de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax Class Reference
template for LaTeX text export
Public Member Functions
final IGrammarComplexElement element (final IGrammarComplexElement p_grammar, final IGrammarComplexElement p_element)
is called if any grammar element is completed
final IGrammarComplexElement grammar (final IGrammarComplexElement p_grammar)
is called on the grammar definition
final void postprocess (final Path p_output) throws IOException, URISyntaxException
postprocessing (after AST visiting)
final void preprocess (final Path p_output) throws IOException, URISyntaxException
preprocessing (before AST visiting)
Public Member Functions inherited from de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate
IBaseTemplate (final String p_name, final String p_index)
ctor
final String index ()
returns the index file
final String name ()
returns the name of the template
Protected Member Functions
final String cardinality (final IGrammarElement.ECardinality p_cardinality, final String p_element)
final String choice (final IGrammarChoice p_element)
final String group (final IGrammarGroup p_element)
final String negation (final IGrammarElement p_element)
final String nonterminal (final IGrammarIdentifier p_element)
final String sequence (final IGrammarCollection p_element)
final String terminalvalue (final IGrammarSimpleElement<?> p_element)
Protected Member Functions inherited from de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate
abstract String cardinality (final IGrammarElement.ECardinality p_cardinality, final String p_element)
sets the cardinality
abstract String choice (final IGrammarChoice p_element)
creates a grammar choice
final void copy (final String p_templatefile, final Path p_output) throws IOException, URISyntaxException
copies files from the directory of the template to the output directory
abstract String group (final IGrammarGroup p_element)
crates a grammer group
String map (final IGrammarElement p_element)
calls the sub routines to format the lement
abstract String negation (final IGrammarElement p_element)
creates a negation structure
abstract String nonterminal (final IGrammarIdentifier p_element)
creates a non-terminal
final void replace (final File p_file, final String... p_replacepair) throws IOException
replaces the string within the file
String rule (final IGrammarRule p_element)
creates a rule
abstract String sequence (final IGrammarCollection p_element)
creates a grammar sequence
String terminal (final IGrammarTerminal p_element)
creates a terminal
abstract String terminalvalue (final IGrammarSimpleElement<?> p_element)
creates a terminal
Package Functions
CLaTeXSyntax (final String p_name)
ctor
Static Private Member Functions
static String escapelatex (final String p_string)
escape string with correct LaTeX definition
Private Attributes
IGrammarComplexElement m_grammar
main grammar
final Table< String, String, String > m_rules = HashBasedTable.create()
rules table for text representation
Additional Inherited Members
Static Protected Member Functions inherited from de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate
static String linkhash (final String p_value)
create a hash of a link
static String removequotes (final String p_string)
removing quotes if needed
Detailed Description
Definition at line 51 of file CLaTeXSyntax.java.
Constructor & Destructor Documentation
CLaTeXSyntax()
de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.CLaTeXSyntax (final String p_name) package
Parameters
p_name template name
Definition at line 67 of file CLaTeXSyntax.java.
Member Function Documentation
cardinality()
final String de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.cardinality (final IGrammarElement.ECardinality p_cardinality, final String p_element) protected
Definition at line 145 of file CLaTeXSyntax.java.
choice()
final String de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.choice (final IGrammarChoice p_element) protected
Definition at line 171 of file CLaTeXSyntax.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarCollection.get().
element()
final IGrammarComplexElement de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.element (final IGrammarComplexElement p_grammar, final IGrammarComplexElement p_element)
Parameters
p_grammar grammar
p_element element
Returns
grammar object reference
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 130 of file CLaTeXSyntax.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement.id(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map().
escapelatex()
static String de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.escapelatex (final String p_string) static private
Parameters
p_string input string
Returns
escaped string
Warning
replace uses character sequences / replaceAll regexp string sequences, so use the correct escaping sequence
See also
https://en.wikibooks.org/wiki/LaTeX/Special_Characters#Other_symbols
Definition at line 213 of file CLaTeXSyntax.java.
References de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.removequotes().
Referenced by de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.terminalvalue().
grammar()
final IGrammarComplexElement de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.grammar (final IGrammarComplexElement p_grammar)
Parameters
p_grammar grammar
Returns
grammar object reference
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 120 of file CLaTeXSyntax.java.
group()
final String de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.group (final IGrammarGroup p_element) protected
Definition at line 182 of file CLaTeXSyntax.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarGroup.element(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map().
negation()
final String de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.negation (final IGrammarElement p_element) protected
Definition at line 200 of file CLaTeXSyntax.java.
References de.flashpixx.rrd_antlr4.CCommon.languagestring(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.map().
nonterminal()
final String de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.nonterminal (final IGrammarIdentifier p_element) protected
Definition at line 194 of file CLaTeXSyntax.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarSimpleElement< T >.get(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.removequotes().
postprocess()
final void de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.postprocess (final Path p_output) throws IOException, URISyntaxException
Parameters
p_output working directory
Exceptions
IOException on io errors
URISyntaxException on uri syntax
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 81 of file CLaTeXSyntax.java.
References de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.copy(), de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement.documentation(), de.flashpixx.rrd_antlr4.antlr.IGrammarComplexElement.id(), de.flashpixx.rrd_antlr4.CCommon.languagestring(), and de.flashpixx.rrd_antlr4.engine.template.IBaseTemplate.replace().
preprocess()
final void de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.preprocess (final Path p_output) throws IOException, URISyntaxException
Parameters
p_output output directory
Exceptions
IOException on io errors
URISyntaxException on uri syntax
Implements de.flashpixx.rrd_antlr4.engine.template.ITemplate.
Definition at line 75 of file CLaTeXSyntax.java.
sequence()
final String de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.sequence (final IGrammarCollection p_element) protected
Definition at line 164 of file CLaTeXSyntax.java.
References de.flashpixx.rrd_antlr4.antlr.IGrammarCollection.get().
terminalvalue()
final String de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.terminalvalue (final IGrammarSimpleElement<?> p_element) protected
Definition at line 188 of file CLaTeXSyntax.java.
References de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.escapelatex(), and de.flashpixx.rrd_antlr4.antlr.IGrammarSimpleElement< T >.get().
Member Data Documentation
m_grammar
IGrammarComplexElement de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.m_grammar private
Definition at line 56 of file CLaTeXSyntax.java.
m_rules
final Table<String, String, String> de.flashpixx.rrd_antlr4.engine.template.CLaTeXSyntax.m_rules = HashBasedTable.create() private
Definition at line 60 of file CLaTeXSyntax.java.